# -*- coding: utf-8 -*-
"""stablediffusion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FBl664_C5FCe4krBQ19xdaTxZM-jyPpf
"""

pip install diffusers

pip install transformers

!pip install diffusers transformers accelerate safetensors torch --quiet

from diffusers import StableDiffusionPipeline

import torch

from PIL import Image

model_id = "runwayml/stable-diffusion-v1-5"

pipe = StableDiffusionPipeline.from_pretrained(
    model_id,
    torch_dtype=torch.float16
)
pipe = pipe.to("cuda" if torch.cuda.is_available() else "cpu")

def generate_image(prompt, guidance_scale, steps):
    image = pipe(
        prompt,
        guidance_scale=guidance_scale,
        num_inference_steps=steps
    ).images[0]
    return image

import gradio as gr

title = "Stable Diffusion Image Generator"
description = "Type a prompt and watch the magic happen! Powered by Stability AI's Stable Diffusion v1-5."

demo = gr.Interface(
    fn=generate_image,
    inputs=[
        gr.Textbox(label="Enter your prompt", placeholder="e.g. a futuristic city skyline at sunset"),
        gr.Slider(1, 15, value=7.5, label="Guidance Scale"),
        gr.Slider(10, 75, value=30, step=1, label="Number of Inference Steps")
    ],
    outputs=gr.Image(label="Generated Image"),
    title=title,
    description=description
)

demo.launch()