# -*- coding: utf-8 -*-
"""Travel planner agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17bCD7m8xOymE0EIyoxnpcCRV4OdyAIv9
"""

pip install langchain duckduckgo-search huggingface_hub

!pip install transformers duckduckgo-search gradio

from transformers import pipeline
from duckduckgo_search import DDGS
import gradio as gr

generator = pipeline("text-generation", model="tiiuae/falcon-7b-instruct", max_new_tokens=300)

def get_weather(location):
    with DDGS() as ddgs:
        results = ddgs.text(f"Weather in {location} this week")
        for r in results:
            return r["body"]

def plan_trip(destination, days, interests):
    prompt = f"Plan a {days}-day trip to {destination} focusing on {interests}. Include historical sites, local food, and fun activities."
    itinerary = generator(prompt)[0]["generated_text"]

    weather = get_weather(destination)
    return f"*Itinerary:\n{itinerary}\n\n🌦️ **Weather Info:*\n{weather}"

gr.Interface(
    fn=plan_trip,
    inputs=[
        gr.Textbox(label="Destination (e.g. Rome)"),
        gr.Slider(1, 10, step=1, label="Number of Days"),
        gr.Textbox(label="Interests (e.g. food, history, culture)")
    ],
    outputs="markdown",
    title="🧳 Free AI Travel Planner",
    description="Uses Falcon-7B and DuckDuckGo to plan a trip and show weather"
).launch()